### ISSUE TITLE
FOB deploys if build animation is cancelled

### ISSUE THREAD

**Issue by JessevGool** [tanaaKa/arma-clash#1]
So basically if you build the fob container but cancel it while you're doing the build animation a respawn will still be created without the FOB itself being there.

Also not able to build

**Comment by tanaaKa** [comment]
Will double check and add it to the fob destruction commit

**Comment by tanaaKa** [comment]
Fixed in https://github.com/tanaaKa/arma-clash/commit/1d11deadbb708f0c83721065be8a8046545d8d35
