### ISSUE TITLE
Error when getting in enemy vehicle.

### ISSUE THREAD

**Issue by FLYlNGHAM** [tanaaKa/arma-clash#20]
Got in a damaged enemy vehicle and got an error. After that I was able to get in a friendly IFV even though I was not in a crew slot. Still got the systemchat 'not crew' message, but it didn't kick me out.
![image](https://user-images.githubusercontent.com/94429186/155434895-4b2e6f0a-b3f7-4b91-b4b7-a48b19e19ee2.png)

**Comment by tanaaKa** [comment]
Fixed in https://github.com/tanaaKa/arma-clash/commit/3a09d227867f69dde6163e135a56932b361bd177
