### ISSUE TITLE
Error when placing a FOB

### ISSUE THREAD

**Issue by FLYlNGHAM** [tanaaKa/arma-clash#21]
![image](https://user-images.githubusercontent.com/94429186/155435727-98ca0c3f-9f96-4a51-900e-a740a9f94088.png)
got this error when building a FOB as OPFOR engineer in the middle of COMM TOWER base. No markers shown on map for me or any teammates.

**Comment by tanaaKa** [comment]
Fixed in https://github.com/tanaaKa/arma-clash/commit/ae3de8497769b6654baf12910941409f6a8dc1ff
