### ISSUE TITLE
Mortar will also need tables

### ISSUE THREAD

**Issue by CrazytheCanuck** [tanaaKa/arma-clash#4]

**Comment by TheTexasHawk** [comment]
1. Include map tools/tables on mortar spawn
2. Add ammo to be purchased?

**Comment by tanaaKa** [comment]
1. Fixed in https://github.com/tanaaKa/arma-clash/commit/d4306a88c62e90c058a5840998c32ecd90125ae3
2. ACE ammo handling has been disabled for the sake of simplicity _for now_
