### ISSUE TITLE
Item shop inventory bug

### ISSUE THREAD

**Issue by TheTexasHawk** [tanaaKa/arma-clash#6]
If you buy an item from the shop and get the message about having a full inventory, you receive the money back but the shop doesn't get restocked with the item it tried to give.

**Comment by tanaaKa** [comment]
Fixed in https://github.com/tanaaKa/arma-clash/commit/d0dd47d73dbdb777b3b92c06e70326d740c50a26

Bought items that no longer fit on your character will be placed in the box next to the PC/buy menu.
